In [1]:
import numpy as np

In [2]:
revenu = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenu - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [8]:
revenu_in_us = np.array([[200,68,110,80],[220,79,140,85],[250,105,180,90]])
inr = 75

In [9]:
revenu_in_inr = np.dot(inr,revenu_in_us)
revenu_in_inr

array([[15000,  5100,  8250,  6000],
       [16500,  5925, 10500,  6375],
       [18750,  7875, 13500,  6750]])

In [10]:
units_sold = np.array([[50,10,40],[60,13,70],[25,5,52]])
price_unit = np.array([20,30,15])

In [11]:
np.dot(price_unit,units_sold)

array([3175,  665, 3680])